### PR TITLE
Fix external cc1101

### PR DESCRIPTION
**Pull request by gid9798**
# What's new

Fix external cc1101 after 2a26680

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gid9798** [comment]
This fixes the problem, but maybe it's not the best way.

Perhaps the problem is in the balance of calls `furi_hal_subghz_start_async_rx` and `furi_hal_subghz_stop_async_rx`.

Or because possible addition of a callback at earlier stages of the system load.

**Comment by xMasterX** [comment]
Changes was reverted for now, ill return to this a bit later

**Comment by Leonardbrett** [comment]
My first investment with Charlotte give me profits of over $7,000 and ever since then she has never failed to deliver and I can even say she's the must sincere broker I have ever known'' communicate with her to be a successful investor. On WhatsApp:+𝟭𝟰𝟳𝟱𝟮𝟰𝟮𝟲𝟯𝟯𝟴

**Comment by xMasterX** [comment]
Hi, there was some changes made in dev after that PR was opened, also your solution was included too in current implementation, but this was not solving whole problem but now when I fixed all other related bugs it should be working fine, thanks anyway

**Pull request closed without merging**
