### PR TITLE
Update filebrowser

### PR DESCRIPTION
**Pull request by ClaraCrazy**
# What's new

- Sort alphabetically. Properly, ofc. Not the semi-broken stuff RM has
- Fix favorites location setting
    - When no favorites are set, the browser would default to /subghz instead of /
- Make sure we display folders before files, always
- Add a "Internal" tab to the Browser
- Stop loading items in weird chunks, which can cause files to be displayed out of order or not at all. This is not a performance issue unless you have over 1k files in a directory, and even then the observed time to load is ~.2 seconds which is barely noticeable

# Verification 

- Open file browser
    - When no favorites are set, you are now in the root dir `Browser`, not `Subghz`
    - When favorites are set, you will see those
    - Pressing left, after being in `Browser` will show the new internals tab
    - Go into a folder with lots of items. (I can not confirm that this issue was as obvious on unleashed as it was elsewhere, but the issue that existed was that files would sometimes be skipped in large folders, or not sorted correctly)

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
https://user-images.githubusercontent.com/55334727/218267055-c12d512c-e4ff-4d04-8e23-3f38613a1c0f.mp4

**Comment by WillyJL** [comment]
Made it show the `---` name and loading icon while the list isn't done loading yet, seems like a fair solution to me :D

**Review by xMasterX — APPROVED** [review]
Big thanks for a great job on fixing and improving that feature
After last changes all works correctly and looks good for eye :)
All tested and will be merged now

**Comment by RocketGod-git** [comment]
Badass, thanks! 🔥🔥🔥

**Comment by ClaraCrazy** [comment]
Just devs helping each other out, as it should be. 

Maybe @RogueMaster should try that once in a while too.

**Pull request merged**
