### PR TITLE
SubGHz: Notifications refines

### PR DESCRIPTION
**Pull request by wosk**
# What's new

SubGHz notifications refines:

- Play error notification on Memory Full state is appearead
- Set IDLE notification (led off) if Memory Full
- Enable Rx notification after deletion of item after "Memory full" state
- Set Rx led indication in receiver info scene according to fullness of memory 
- Restore line position after return from Exit confirmation dialog

# Verification 

Check led notifications after wander around menus

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by xMasterX — CHANGES_REQUESTED** [review]
Hi, I sent you video showing issues that PR has, in our telegram group, please fix these problems, thanks!

**Review by xMasterX — CHANGES_REQUESTED** [review]
1. Error notification appears every time when memory is full and you opening and closing one of received signals
2. `Restore line position after return from Config scene` -> Cursor position works ok even without these changes, can you describe test cases what this PR should change except error notification and restoring rx indication after delete when memory is full?

**Comment by xMasterX** [comment]
I will apply fix from your PR separately `Restore Rx indication after deletion after "Memory is FULL"`
Thanks
but while found issues is not resolved I can't merge that in current condition

**Comment by wosk** [comment]
> 1. Error notification appears every time when memory is full and you opening and closing one of received signals

I guess it's ok to notify user, that no more signals will be recevied.
> 2. `Restore line position after return from Config scene` -> Cursor position works ok even without these changes, can you describe test cases what this PR should change except error notification and restoring rx indication after delete when memory is full?

If you push the back button twice, the cursor position is reset.
[Don't reset cursor position after 2x Back btn press](https://github.com/DarkFlippers/unleashed-firmware/pull/464/commits/c9590ead711fd2c7760f020723f925682eea6ddc)
I'll fix the item in the description

**Comment by wosk** [comment]
> 1. Error notification appears every time when memory is full and you opening and closing one of received signals
Agree, fixed - Error notification appears only when the 55th signal has been received.

**Review by xMasterX — APPROVED** [review]
All seems to be working ok now, thanks

**Pull request merged**
