### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Flores-21**
# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by Flores-21 — COMMENTED** [review]
I

**Comment by Flores-21** [comment]
> # What's new
> * [ Describe changes here ]
> 
> # Verification
> * [ Describe how to verify changes ]
> 
> # Checklist (For Reviewer)
> * [x]  PR has description of feature/bug
> * [x]  Description contains actions to verify feature/bugfix
> * [x]  I've built this code, uploaded it to the device and verified feature/bugfix

**Comment by Flores-21** [comment]
K

**Comment by assasinfil** [comment]
Fix conflicts

**Pull request closed without merging**
