### PR TITLE
Browser: Context menu to show file content

### PR DESCRIPTION
**Pull request by askoriy**
# What's new

- There is an ability to view the files content directly on the Flipper. It could be useful to review BadUsb scripts before run, read README and notes for collection of downloaded artifacts, view all data from saved NFC, etc.

# Verification 

- Now all files in Browser have additional context menu item **Show** right after **Info**.

# Limitations
- With current implementation all file content is loaded into memory. Maximum file size is limited by 20K to not crash the Flipper.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by RogueMaster** [comment]
Do you have it limited to certain file types? (.txt, .md for example...)

Any option to add text?

Not sure what Nano thinks, but, I feel like your archive scene show should be it's own app that can view/edit text in files and you can direct the "Show" option to that FAP with the method used on this PR https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/382

**Comment by RogueMaster** [comment]
You could also check the file size and not open the file if it is too big to open...

**Comment by xMasterX** [comment]
> Do you have it limited to certain file types? (.txt, .md for example...)
> 
> Any option to add text?
> 
> Not sure what Nano thinks, but, I feel like your archive scene show should be it's own app that can view/edit text in files and you can direct the "Show" option to that FAP with the method used on this PR [RogueMaster#382](https://github.com/RogueMaster/flipperzero-firmware-wPlugins/pull/382)

I modified it with added checks for file types and with some fixes
Also no need to make it external .fap since change itself is not that big

**Review by xMasterX — APPROVED** [review]
Thanks for PR, after my little changes seems pretty stable

**Pull request merged**
