### PR TITLE
feature[animation]: purple rain animation

### PR DESCRIPTION
**Pull request by wotori**
# What's new
- new animation

# Verification 
- check images and this gif
output

# Checklist (For Reviewer)
- [x] PR has description of feature/bug
- [X] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by wotori** [comment]
for a some reason got this build errors, what is the problem?
```
Exception: Meta file is invalid: incorrect data
scons: *** [assets/resources/dolphin/L1_Boxing_128x64/frame_0.bm] Error 1
********** ERRORS **********
Failed building assets/resources/dolphin/L1_Boxing_128x64/frame_0.bm: Error 1
```

**Comment by wotori** [comment]
> for a some reason got this build errors, what is the problem?
> 
> ```
> Exception: Meta file is invalid: incorrect data
> scons: *** [assets/resources/dolphin/L1_Boxing_128x64/frame_0.bm] Error 1
> ********** ERRORS **********
> Failed building assets/resources/dolphin/L1_Boxing_128x64/frame_0.bm: Error 1
> ```

this error was fixed with updates of meta file

**Comment by wotori** [comment]
improved compatibility with the status bar
output

**Comment by xMasterX** [comment]
Hi, thanks for PR, you did a great job, but animation doesn’t fit in current style, sorry, if you could change it a bit I can accept it, check out our custom animations and official animations for example

**Review by xMasterX — CHANGES_REQUESTED** [review]
details in previous comment

**Comment by RogueMaster** [comment]
When you say style, do you mean mainly the style of the dolphin layer?

**Comment by xMasterX** [comment]
> When you say style, do you mean mainly the style of the dolphin layer?

Yes, and about details too
Our custom anims went through many many changes and polishing to be included in releases
This one needs some polishing too :)

**Comment by xMasterX** [comment]
Reopen if you want to make changes, thanks!

**Pull request closed without merging**
