### PR TITLE
Barcode generator: rfct, ux improvements, implement EAN-8.

### PR DESCRIPTION
**Pull request by msvsergey**
# What's new

- Code is totally refactored (removed similar functions for every digit, increased readability by introducing enum and constants for view modes/menu items, other improvements).
- Implemented EAN-8 [(issue)](https://github.com/DarkFlippers/unleashed-firmware/issues/151)
- UX improvements: align elements, correctly handle ok and back buttons.

# Verification 

- Make sure both UPC-A and EAN-8 are working correctly.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by xMasterX — APPROVED** [review]
All tested fine, thanks for PR, thats a good improvement for this plugin

**Comment by Bon-Jorik** [comment]
Could you add EAN-13 type barcode gen? It's the most used for everything

**Comment by mhafizhandi** [comment]
Hi, just to feedback that Code-128 doesn't seems to work as it says 'Missing Encoding Table'
Missing Encoding Table

**Comment by xMasterX** [comment]
> Hi, just to feedback that Code-128 doesn't seems to work as it says 'Missing Encoding Table'
> Missing Encoding Table

Wrong repo, there is no code 128 in this PR or in this whole repo

**Comment by mhafizhandi** [comment]
> > Hi, just to feedback that Code-128 doesn't seems to work as it says 'Missing Encoding Table'
> > Missing Encoding Table
> 
> Wrong repo, there is no code 128 in this PR or in this whole repo

Apologies my bad. yea, no Code-128 after a fresh update. was trying to save some of the cards to test on them. 👍

**Pull request merged**
