### PR TITLE
Emv fixes

### PR DESCRIPTION
**Pull request by wosk**
# What's new

- Gazprombank card read crash fixed
- Parser improvements (cardholder name parsing, some EMV cards that was not able to parse before this PR is now able to parse)
- EMV protocol detect false positive result fixed
- Transactions render fixed

# Verification 

- Read Gazprombank EMV card. Make sure that flipper doesnt crash

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by Leptopt1los — APPROVED** [review]

**Review by Leptopt1los — CHANGES_REQUESTED** [review]
Unable to load saved dump

**Comment by WillyJL** [comment]
FYI, im seeing empty transaction history on my mastercard with this PR's changes, shows fine without. not sure where exactly the issue would be, dont see any changes related to transactions at a first sweep through the diff...

either way great work, looking forward to this :)

**Comment by WillyJL** [comment]
i was able to get transaction history to work again for my mastercard by reverting the `emv_poller_read_afl()` function to its state before this PR. i found this by looking at logs, stripping out most of them and looking for the SFI attempts, this is what I see:

working (gets transaction history) (dev branch):
```
[T][EMVPoller] SFI 0x2 record 1:
[T][EMVPoller] SFI 0xB record 1:
[T][EMVPoller] SFI 0xB record 2:
[T][EMVPoller] SFI 0xB record 3:
[T][EMVPoller] SFI 0xB record 4:
[T][EMVPoller] SFI 0xB record 5:
[T][EMVPoller] SFI 0xB record 6:
[T][EMVPoller] SFI 0xB record 7:
[T][EMVPoller] SFI 0xB record 8:
[T][EMVPoller] SFI 0xB record 9:
[T][EMVPoller] SFI 0xB record 10:
```

broken (no transactions info) (pr head):
```
[T][EMVPoller] SFI 0x2 record 1:
[T][EMVPoller] SFI 0x4 record 1:
[T][EMVPoller] SFI 0x4 record 2:
[T][EMVPoller] SFI 0x4 record 3:
[T][EMVPoller] SFI 0x4 record 4:
[T][EMVPoller] SFI 0x2 record 2:
[T][EMVPoller] SFI 0x3 record 1:
```

**Comment by Leptopt1los** [comment]
@Willy-JL Thank you! the problem was that the attempt to brute force files 2-3 was before reading transactions. Some cards, after attempting to read a record that does not exist on them, refuse to respond to subsequent requests. this seems to be done for security reasons

**Comment by Leptopt1los** [comment]
@wosk thank you for the productive collaboration!

**Review by Leptopt1los — APPROVED** [review]

**Review by xMasterX — APPROVED** [review]

**Comment by WillyJL** [comment]
can confirm the transactions work again, thanks!

**Pull request merged**
