### PR TITLE
Add compile on push workflow

### PR DESCRIPTION
**Pull request by SticksDev**
# What's new

This PR leverages github's built in actions to build and compile the FW on a push or a pr open. It uses the default toolchain 
as provided in the docs.

# Verification 

Run workflow, it will compile an unoptimized build (dev) and a prod build (used in the updater) - these files will output in the action outputs.

Action Output

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by PraveenNanda124 — COMMENTED** [review]
Looks good

**Comment by m1ga** [comment]
a side note: I've made that PR a while ago https://github.com/DarkFlippers/unleashed-firmware/pull/167 
It can be shorter (no need to install the packages by hand) but it was already closed becaues it wasn't needed.

**Comment by xMasterX** [comment]
Hello, CI/CI infrastructure are built on drone CI, i don't want to move it to github actions
And also PRs should not be built automatically, this also doesn’t make sense, I’m checking every change manually, if you seen official repo, they not building someones PRs too

**Comment by SticksDev** [comment]
I can easily move this over to drone, what do you want the requirements to
be for it to run?

**Comment by xMasterX** [comment]
> I can easily move this over to drone, what do you want the requirements to be for it to run?

What you want to move, PR auto builds?

It will not happen, i told you, read my previous reply

If you talking about building every commit pushed to dev, looks like you haven’t seen that's already been done, dev build links are in readme

**Pull request closed without merging**
