### PR TITLE
New frequency analyzer

### PR DESCRIPTION
**Pull request by ClusterM**
# What's new

New frequency analyzer view:
* Ability to set RSSI trigger level
* Sound and vibration on signal detect
* The last detected frequency is displayed
* The interface looks better

image

# Verification 

* Start "Sub-GHz"
* Select "Frequency Analyzer"
* Check out the new Frequency Analyzer!
* Try to generate any signal nearby
* "Success" sound and vibration should be played
* The last frequency value and the last RSSI level should be displayed
* You can press left and right to set RSSI trigger level

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by MassivDash** [comment]
According to this PR: I should have the ability to "press left and right to set RSSI trigger level", but this is not the case, if I set the RSSI above the found levels, flipper still pick's up signals below the threshold. Is there some kind of additional setting to be used here for this to work properly ?

**Comment by xMasterX** [comment]
This trigger only affects notifications not display, sensitivity was changed a bit so it now pickups more signals and noise too

**Comment by ClusterM** [comment]
> This trigger only affects notifications not display, sensitivity was changed a bit so it now pickups more signals and noise too

Yes. Notifications and "last" value.

**Comment by samysousa** [comment]
Hi @ClusterM , Amazing work here. 
Any proper place or way to make a feature request ?
- Log Detected Frequencies. (They go by too fast).
Or
- On Button Press "Save Last detected to Log file" 

Something like that would be very practicle (along with Detected power level and more).

**Pull request merged**
