### PR TITLE
[FEAT] Save hopping state in SubGHz

### PR DESCRIPTION
**Pull request by derskythe**
# What's new

Hi **xMasterX**, how you doing? 
My another approach to save all settings in SubGHz. It's tested for a few weeks on a real device.

- Save Hopping state and preset in last settings
- Save state of: 
  - BinRAW 
  - Ignore Starline
  - Ignore Cars
  - Ignore Magellan
- Also added compatibility with Read RAW mode
- Change caption on scanning screen (`SubGhz -> Read`) to `Fixed scan...` for fixed frequency and `Hopper scan...` for hopping mode
- Add `subghz_last_settings_log` to easy log last settings state
- Add to CLI command `l` alias for `log`
- Some refactor and change some types to correct value 

# Verification 

- Change last settings
- Close app
- Run app again and go to Read mode 

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by gid9798** [comment]
Hi. It might be worth adding "reset configuration" in `receiver_config`

**Comment by derskythe** [comment]
> Hi. It might be worth adding "reset configuration" in `receiver_config`

@gid9798 you mean delete all last settings? But why?

**Comment by Hatermakerbaby** [comment]
Nice

**Comment by gid9798** [comment]
> > Hi. It might be worth adding "reset configuration" in `receiver_config`
> 
> @gid9798 you mean delete all last settings? But why?

This is like a quick way to reset the operating mode to the "default" state.

1. Convenient when reading a new "unknown key"
2. It is useful for users who like to press buttons without understanding their meaning.(It is unlikely that they will remember how it was originally)

**Comment by derskythe** [comment]
@gid9798 ok, I'll be back with an update

**Comment by xMasterX** [comment]
Will be merged after "reset config" button will be added, waiting for updates, will mark as draft for now
Thanks

**Comment by derskythe** [comment]
@xMasterX, @gid9798 "Reset to default" feature was added

Screenshot-20230910-023816

**Review by xMasterX — APPROVED** [review]

**Pull request merged**
