### PR TITLE
Decreased power off interval

### PR DESCRIPTION
**Pull request by azaitsev**
# What's new

- Decreased power off interval. Even 2 seconds are 10 times more than just a long press.

# Verification 

- Press the back button on the desktop for two seconds

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
Hi, thanks for PR, i see no reason for lowering that value to 2 seconds, as flipper is usually always on, and 5 secs is ok if you really want to turn it off, with screen backlight off it can work for very long time
Thats done on a purpose, to be like tamagotchi 

I think lowering for 3 seconds is ok, you can change value and commit it to this PR, i will merge it after that

**Comment by azaitsev** [comment]
Flipper is not a tamagotchi, it's a specialised device for working with signals. I only turn the flipper on when I need it and turn it off after each time. There is no need to keep the flipper on all the time and charge it every week.

**Comment by xMasterX** [comment]
If you read my message, I said "to be like tamagotchi", it has that as secondary functionality

As I said, 3 seconds will be fine, I can add that if you commit changes

**Comment by xMasterX** [comment]
I set that value to 3 sec
See commit:
https://github.com/Eng1n33r/flipperzero-firmware/commit/29f2358f75dd4b480b8886e4a91014d296aaec91

**Pull request closed without merging**
