### PR TITLE
Disable Christmas Animations

### PR DESCRIPTION
**Pull request by SkeletonMan03**
# What's new

- Updated Manifest to disable Christmas animations

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
I kept them cuz official firmware still has them enabled in RC version too

**Comment by SkeletonMan03** [comment]
Ah, I figured there was a reason they were still there

**Comment by xMasterX** [comment]
Ill disable them in next releases, ill keep this PR open then

**Comment by xMasterX** [comment]
Holiday anim was removed in ofw but L1_Sleigh_ride_128x64 is still here, since its still winter outside i think thats why they kept it, so ill close this PR for now

**Pull request closed without merging**
