### PR TITLE
Autolock with pin code

### PR DESCRIPTION
**Pull request by WillyJL**
# What's new

- Desktop autolock uses pin code

# Verification 

- Set pin code, enable autolock, wait, flipper locked with pin

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by Slippin12b — COMMENTED** [review]
I need some help, I don't recall how,  but I set this up but I don't remember my pin is there a default pin?

**Comment by ClaraCrazy** [comment]
absolute bozo moment. no theres no default pin. the pin is whatever you have set lol.

**Review by xMasterX — CHANGES_REQUESTED** [review]
Hi, one problem with this change, it actually replaces auto keyboard lock with pin lock
When i have Pin set-up i can choose to lock with pin or not in top menu, but there it will just replace auto lock to use only pin if i have one, 

It should be re-done in different way, for example we can add
`bool autolock_with_pin;` into `DesktopSettings` in `applications/services/desktop/desktop_settings.h`
And make UI selector in desktop settings app `Auto Lock with pin: ON / OFF`
And there we can just add 
```
if (desktop->settings.autolock_with_pin){
    if(desktop->settings.pin_code.length > 0) {
```
and we will use pin lock, in other case we will just call regular lock as it is done now


I can make that changes myself but later, tell me if you gonna make it optional as i described

**Comment by WillyJL** [comment]
Hm you're right, that's a good idea! Will do it myself, don't worry.

**Review by xMasterX — APPROVED** [review]
Thanks! 
I made small change, all details described in my last commit in its desc
All works as it should

**Pull request merged**
