### PR TITLE
adding support for HIDProx, updating the UI to switch between protocols

### PR DESCRIPTION
**Pull request by mvanzanten**
- Adding support for HIDProx
- Updating the UI to allow for protocol switching
- Update README.md to reflect changes made

### CODE REVIEW

**Comment by xMasterX** [comment]
Thank you for PR! That's a good addition to rfid fuzzer plugin
I will verify it in next hour and it will be merged asap

**Comment by mvanzanten** [comment]
Awesome thanks!

**Comment by xMasterX** [comment]
All works fine, thanks!

**Comment by mvanzanten** [comment]
Thanks!

**Pull request merged**
