### PR TITLE
Add Extended Keyboard

### PR DESCRIPTION
**Pull request by 1333481**
# What's new

- Added Extended Keyboard from Xtreme
# Verification 

- Open something that uses the keyboard

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
Hi, remove extra symbols from keyboard then i will accept that, that symbols is not allowed for system keyboard!

Flipper file system is very strict about file names, it could accept some symbols but in most cases it will lead to issues
System keyboard should be minimal since it used in system only for file naming, and in some plugins that was built without support for that symbols!

Plugins that require extra symbols have their own keyboard, like UART Terminal

**Review by xMasterX — CHANGES_REQUESTED** [review]
Did you read my previous message?

**Comment by 1333481** [comment]
> Did you read my previous message?

I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.

**Comment by xMasterX** [comment]
> > Did you read my previous message?
> 
> I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.

You are replacing entire system keyboard, not in wifi marauder, in whole system
Read my first message, i told you why this should not be done
Make requested changes and I will accept this PR

**Comment by 1333481** [comment]
> > > Did you read my previous message?
> > 
> > I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.
> 
> You are replacing entire system keyboard, not in wifi marauder, in whole system
> Read my first message, i told you why this should not be done
> Make requested changes and I will accept this PR

It's fine if you don't want to merge it, I just thought to make a pr if you night want to do that but I understand. The only thing in this pull request is the keyboard with symbols so if I change it will be just like stock.

**Comment by xMasterX** [comment]
> > > > Did you read my previous message?
> > > 
> > > 
> > > I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.
> > 
> > 
> > You are replacing entire system keyboard, not in wifi marauder, in whole system
> > Read my first message, i told you why this should not be done
> > Make requested changes and I will accept this PR
> 
> It's fine if you don't want to merge it, I just thought to make a pr if you night want to do that but I understand. The only thing in this pull request is the keyboard with symbols so if I change it will be just like stock.

What extra symbols needed for wifi marauder app? I can add them in that particular plugin

**Comment by 1333481** [comment]
> > > > > Did you read my previous message?
> > > > 
> > > > 
> > > > I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.
> > > 
> > > 
> > > You are replacing entire system keyboard, not in wifi marauder, in whole system
> > > Read my first message, i told you why this should not be done
> > > Make requested changes and I will accept this PR
> > 
> > It's fine if you don't want to merge it, I just thought to make a pr if you night want to do that but I understand. The only thing in this pull request is the keyboard with symbols so if I change it will be just like stock.
> 
> What extra symbols needed for wifi marauder app? I can add them in that particular plugin

It was the dash symbol. I figure out I could just type out the command in the uart terminal but it would be just a nice Quality of life feature

**Comment by xMasterX** [comment]
> > > > > > Did you read my previous message?
> > > > > 
> > > > > 
> > > > > I ported this keyboard over from other custom firmware because I noticed the wifi maurauder doesn't have a special keyboard.
> > > > 
> > > > 
> > > > You are replacing entire system keyboard, not in wifi marauder, in whole system
> > > > Read my first message, i told you why this should not be done
> > > > Make requested changes and I will accept this PR
> > > 
> > > 
> > > It's fine if you don't want to merge it, I just thought to make a pr if you night want to do that but I understand. The only thing in this pull request is the keyboard with symbols so if I change it will be just like stock.
> > 
> > 
> > What extra symbols needed for wifi marauder app? I can add them in that particular plugin
> 
> It was the dash symbol. I figure out I could just type out the command in the uart terminal but it would be just a nice Quality of life feature

Good, I will make some changes in wifi marauder plugin in 044 release, thx for info

**Comment by WillyJL** [comment]
For the record I have updated the keyboard on Xtreme removing the illegal characters that made FatFS (and Windows) complain, now it works flawlessly on Flipper and qFlipper sees all files perfectly fine.

From my extensive testing I have found no issues with this new symbol list (I didn't however test the mobile apps, they are completely useless IMO), but it's up to Nano if he wants to merge this, its not really a needed feature (apart from the - for marauder commands) but more like letting the user do what they want.

And of course this PR includes our movable textbox cursor too, which is not strictly necessary but really useful (noticed it wan't mentioned anywhere in here).

**Comment by paradiselabs-ai** [comment]
> And of course this PR includes our movable textbox cursor too, which is not strictly necessary but really useful (noticed it wan't mentioned anywhere in here).

What do you mean movable text box cursor? Typing in the flipper is so GD annoying, I've been thinking about sometimes using my phone to do any typing or text editing , which isn't as fun cus I text on my phone all the time and the flipper is really kinda an experience made to use on its own.... 

Haha now im imagining some elaborate PCB that has Wifi/subghz/whatever modules on the top like normal but all being soldered into a long custom pcb that wraps around the back of it and puts a small physical button QWERTY at the bottom, in an almost smart or flip phone style to either hold with one hand and type but preferably with both hands... it would have to have a pretty sturdy plastic covering on the backside of it that maybe somehow clipped onto the flipper itself to keep the pcb board from snapping or the pine bending (of course i can't afford custom PCB or have any 3D printing so anything custom I make looks pretty jank lol, I'm kinda a mess with hardware

**Pull request closed without merging**
