### PR TITLE
Added 1 audio device, 2 projectors and 1 tv

### PR DESCRIPTION
**Pull request by f-mns**
# What's new

- AEG Radio, NEC and Rayfoto projector and a Sweex tv

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Review by amec0e — CHANGES_REQUESTED** [review]
Firstly thank you for the contribution! Secondly I would greatly appreciate it if you could message me with your additions on discord (you can find me in the unleashed discord with ease) and I will check over them and if they are all good they will be added to the assets. This is because there is a thorough process that takes place before any changes are made to the infrared assets, when directly uploaded these checked are skipped and duplicate entries can be introduced.

Lastly!

MUTE in audio.ir is a duplicate entry, please remove that button you added.

POWER in tv.ir is a duplicate entry, please remove that button you added.

**PS:** Time stamps also need updating

**Comment by f-mns** [comment]
Unfortunately i don't want to / can't use discord in the future I'm sorry. But I fixed the 2 buttons!

**Review by PraveenNanda124 — COMMENTED** [review]
Looks good

**Comment by pedroCX486** [comment]
> Firstly thank you for the contribution! Secondly I would greatly appreciate it if you could message me with your additions on discord

I really stopped reading here. PR discussions exist for this exact matter. Discord is not needed for that. Discord is not a transparent easily searchable content provider accessible by search engines.

OpenSource projects shouldn’t be doing this.

**Review by amec0e — COMMENTED** [review]
Hey there, appreciate you don't want to use discord, this just means it will take longer to get around to it because I am one person managing 5 assets along with going through our discords IR files that are uploaded and 4 other github repositories to keep these maintained. Most of my time is spent helping our discord users and working with them to get the best captures as interference is quite common and can be easy to spot. However I simply cannot be in two places at once.

Additions have been added to the asset files and they will be pushed out with the next assets update. The PR will be close as if merged there will be a lot of community contributions will be lost as the assets have since been updated.

**Pull request closed without merging**
