### PR TITLE
Updated Universal Remote (all buttons)

### PR DESCRIPTION
**Pull request by UberGuidoZ**
# What's new

- Adds the ability to use the volume/channel buttons within the existing Universal remote

# Verification 

- Compiled by Hyper_Mash with support/testing by UberGuidoZ
- Verified on current firmware releases (Official, Unleashed, RogueMaster)
- Remote can freeze up to 10 seconds at a time; this is normal while it skips other button functions.
- EVERY button completes and does not crash; size optimized and tested.
- Plan to maintain with additions as they come in from other IR files AND more organization.
- Lastly, plans to add other devices beyond TV (AV, AC, etc.)

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device, and verified the feature/bugfix

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
Currently hosted here: https://github.com/UberGuidoZ/Flipper/tree/main/Infrared
Discussion started: https://discord.com/channels/740930220399525928/954422774141710366/993703699316756561
Released: https://discord.com/channels/740930220399525928/954422774141710366/994119260139950130
Optimized: https://discord.com/channels/740930220399525928/954422774141710366/994120897780781106
Tested: https://discord.com/channels/740930220399525928/954422774141710366/994123369148588072

**Comment by Eng1n33r** [comment]
Need to test.

**Comment by Eng1n33r** [comment]
Pls check your asset. Flipper is freezing (until hard reset) on bruting buttons.

**Comment by UberGuidoZ** [comment]
Line 3 of verification - known "issue" as it's skipping other buttons. It will finish if left for 10-15 seconds.

**Pull request merged**
