### PR TITLE
FlipFrid - uprade

### PR DESCRIPTION
**Pull request by Ganapati**
# What's new

- Removed bad crc attack
- Add fuzzing from existing dump 
- Changed UI

### CODE REVIEW

**Review by S2ciOnur — APPROVED** [review]
LGTM

**Comment by azaitsev** [comment]
Why did you remove bad crc attack?

**Comment by quantum-x** [comment]
Hi @xMasterX -
Any chance to remove the hardcoded minimum "time_between_cards" ? 
On certain readers, 0 delay causes overflows which opens the lock.
When the delay is forced to a minimum of 5s, this behaviour no longer works.

**Comment by Commmaned** [comment]
Instructions unclear now locked in Area 51

**Pull request merged**
