### PR TITLE
Fixes and improvements

### PR DESCRIPTION
**Pull request by DevMilanIan**
# What's new

- Add a visual representation of your lives, a score counter, and use the free_and_exit method to prevent NULL pointer dereference

# Verification 

- Play some arkanoid and notice your lives on the left, score on the right, and that you don't crash if you'd like to exit and come back.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by xMasterX** [comment]
Hi, Thanks for PR, I also have plans to re-do some things in this game, but its low priority now
For example, bunch of vars on top should be replaced with struct
Also it has many unused things, like `intro` function
So it will be great if someone could fix that things

**Comment by kiwidotcom** [comment]
Hi

I'm writing this for a friend who is completely new to this but wants to
learn he's lucky enough to have a working flipper and has the unleashed
firmware on it what states it can clone remotes etc with rolling codes how
does this work because I've tried my garage remote and it will not work
adult he's also tried his garage remote and the same thing are we doing
something wrong or missing something any kind advice would be greatly
appreciated and to the developer behind the unleashed firmware thank you
for all your hard work without people like you us knew people would not be
able to get full potential out of their devices
T

**Comment by DevMilanIan** [comment]
> Hi I'm writing this for a friend who is completely new to this but wants to learn he's lucky enough to have a working flipper and has the unleashed firmware on it what states it can clone remotes etc with rolling codes how does this work because I've tried my garage remote and it will not work adult he's also tried his garage remote and the same thing are we doing something wrong or missing something any kind advice would be greatly appreciated and to the developer behind the unleashed firmware thank you for all your hard work without people like you us knew people would not be able to get full potential out of their devices T


Hey! Glad more people are getting involved with the flipper, the best way to find out is by joining the links for chatrooms, telegrams, or discord servers and getting involved with the community. This repo has one on it's main page and there are many more! Good luck :)

**Comment by UberGuidoZ** [comment]
Thanks for the quick turnaround, @DevMilanIan, and for helping someone new when they clearly needed it. =)

**Pull request merged**
