### PR TITLE
Update one word in name_generator.c

### PR DESCRIPTION
**Pull request by Im-CatDev**
Changed one of the words because it is an offensive word in some language

# What's new

- [ Changed one of the words because it is an offensive word in some language ]

# Verification 

- [ What is there to verify here? I changed only one word in the list ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by mishamyte** [comment]
So how can users randomly generate kurwa animals after? It's an Easter Egg, so 😐

**Comment by xMasterX** [comment]
sorry, its not meant as "bad word"

https://www.youtube.com/watch?v=OHHpYXQyQO4

**Comment by Im-CatDev** [comment]
But anyways, why not keep it family-friendly?

**Comment by derskythe** [comment]
Disagree!

**Comment by derskythe** [comment]
> But anyways, why not keep it family-friendly?

@Im-CatDev children are learning quickly now. They still learn bad words. 
And it would be better if it were us than someone from a wrong neighborhood.

**Comment by Im-CatDev** [comment]
you're kinda right

**Pull request closed without merging**
