### PR TITLE
New battery display (Bar %)

### PR DESCRIPTION
**Pull request by Fasjeit**
# What's new

* New battery display (combining default bar with percent display)
* Defining constants for Battery Display Types in [desktop_settings.h](https://github.com/DarkFlippers/unleashed-firmware/compare/dev...Fasjeit:unleashed-firmware:dev?expand=1#diff-553a0eead9efeb45e7207a7fe16d6c10ce763a782cf2e5b4c0a7c0290a61b13f)

bat_6
bat_46
bat_76
bat_100
bat_charging_100_2

# Verification 
* Select `Bar %` in `Settings/Desktop/Battery View`
* Plug in charging cable

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by TQMatvey** [comment]
yeah seems cool, should get merged

**Comment by Fasjeit** [comment]
Now with its own charging level!
bat_charging_79

**Comment by peterlewis** [comment]
Love this! Thank you so much for implementing it.

**Comment by RogueMaster** [comment]
Thank you! I have added this to RM too

**Review by xMasterX — APPROVED** [review]
Thanks!

**Pull request merged**
