### PR TITLE
Merge spectrum analyzer

### PR DESCRIPTION
**Pull request by djsime1**
# What's new

Added spectrum analyzer plugin

# Verification 

Compiled and flashed to my own device, tested using keyfob with known frequency.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by djsime1** [comment]
Compiled firmware: https://cdn.dj.je/ShareX/0522/flipper-z-f7-full-local-40b0efc9.dfu

**Comment by Eng1n33r** [comment]
Great job!

**Comment by Eng1n33r** [comment]
@djsime1 Pls check the code, Spectrum Analyser doesn't working!

**Comment by djsime1** [comment]
I'm going to need more than a "isn't working" to fix this. What specifically isn't working?

**Pull request merged**
