### PR TITLE
External CC1101 support

### PR DESCRIPTION
**Pull request by quen0n**
# What's new

- Added external CC1101 support

# Verification 

- Connect CC1101 module
- Go to menu -> Sub GHz -> Radio settings -> Module. Swtich to "external"
- Try to receive or send radio signals

# Checklist (For Reviewer)

- [x] PR has description of feature/bug
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by awnyel** [comment]
Thats Cool!

**Comment by emoisemo** [comment]
Looking forward, is module based on nrf24??

**Comment by xMasterX** [comment]
> Looking forward, is module based on nrf24??

 no, this is different module

**Review by xMasterX — APPROVED** [review]
I did tests and made some changes to fix gui issues, all plugins works correctly with external module, and RX / TX in main subghz app works correctly, existing protocols decoded without issues

Thanks for a great work

**Comment by oldbug62** [comment]
I have tested it the reception is much better thank you. Is it possible to receive and transmit with another module under 300 Mhz?

**Pull request merged**
